name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      DOC_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Python up
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Material for MkDocs
        run: pip install --requirement requirements.txt

      - name: Build documentation
        run: mkdocs build

      - name: Transform the URLs
        run: python ./scripts/transform_urls.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          # role-session-name: GitHubActionUserDocDeployment

      - name: Copy files to the test website with the AWS CLI
        run: aws s3 sync --delete --quiet ./site s3://${{ secrets.BUCKET_NAME }}

      # KLUDGE: Clearing the whole cache is overkill but determining what items to invalidate is hard
      - name: Invalidate CloudFront cache
        run: |
              aws cloudfront create-invalidation \
                --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                --paths "/*"
