name: Sync Docs to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync markdown files to R2
        run: |
          aws s3 sync docs/ s3://${{ secrets.R2_BUCKET_NAME }}/spacelift-docs/ \
            --endpoint-url ${{ secrets.R2_ENDPOINT_URL }} \
            --exclude "*" \
            --include "*.md" \
            --delete
  sync-unchunked:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.UNCHUNKED_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.UNCHUNKED_R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync markdown files to R2
        run: |
          aws s3 sync docs/ s3://${{ secrets.UNCHUNKED_R2_BUCKET_NAME }}/ \
            --endpoint-url ${{ secrets.UNCHUNKED_R2_ENDPOINT_URL }} \
            --exclude "*" \
            --include "*.md" \
            --delete
